import type { Metadata } from "next";
import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer";
import ConfigureAmplifyClientside from "./amplify-cognito-config";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  session,
}: Readonly<{
  children: React.ReactNode;
  session?: any;
}>) {
  // const session = await auth;
  return (
    <html lang="en">
      <body>
        <ConfigureAmplifyClientside/>
          <Header/>
          {children}
          <Footer/>
      </body>
    </html>
  );
}
