import type { Metadata } from "next";
import "./globals.css";
import SessionProvider from "./components/sessionProvider";
import Header from "./components/Header";
import Footer from "./components/Footer";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  session,
}: Readonly<{
  children: React.ReactNode;
  session?: any;
}>) {
  // const session = await auth;
  return (
    <html lang="en">
      <body>
        <Header/>
        <SessionProvider session={session}>{children}</SessionProvider>
        <Footer/>
      </body>
    </html>
  );
}
