// import type { Metadata } from "next";
// import "./globals.css";
// import SessionProvider from "./components/sessionProvider";



// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default async function RootLayout({
//   children,
//   session,
// }: Readonly<{
//   children: React.ReactNode;
//   session?: any;
// }>) {
//   // const session = await auth;
//   return (
//     <html lang="en">
//       <body>
//         <SessionProvider session={session}>{children}</SessionProvider>
//       </body>
//     </html>
//   );
// }




import React from "react";
import { Link, useLocation } from "react-router-dom";
import { createPageUrl } from "@/app/utils/utils-url";


export default function Layout({ children, currentPageName }) {
  return (
    <div className="min-h-screen bg-gradient-to-b from-slate-50 to-white">
      <style>
        {`
          :root {
            --primary-indigo: #4338ca;
            --primary-purple: #7c3aed;
            --accent-gold: #f59e0b;
            --luxury-gray: #1f2937;
            --soft-gray: #f8fafc;
          }
          
          .luxury-gradient {
            background: linear-gradient(135deg, var(--primary-indigo) 0%, var(--primary-purple) 100%);
          }
          
          .gold-accent {
            color: var(--accent-gold);
          }
          
          .premium-shadow {
            box-shadow: 0 25px 50px -12px rgba(0, 0, 0, 0.08);
          }
          
          .glass-effect {
            background: rgba(255, 255, 255, 0.95);
            backdrop-filter: blur(10px);
            border: 1px solid rgba(255, 255, 255, 0.2);
          }
        `}
      </style>
      {children}
    </div>
  );
}